# permissions for end users to edit ovhnginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ovhnginx-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-go-operator
    app.kubernetes.io/part-of: nginx-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: ovhnginx-editor-role
rules:
- apiGroups:
  - tutorials.ovhcloud.com
  resources:
  - ovhnginxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tutorials.ovhcloud.com
  resources:
  - ovhnginxes/status
  verbs:
  - get
